-- Fixed dropdown vocabulary for the requisition form, sourced from ZingHR.
--
-- Departments, each department's sections, designations, the grades valid for
-- each designation, and the posting zones. Seeded here rather than in
-- prisma/seed.ts because that seed must never run against production (it also
-- upserts the admin user, units, departments, positions and sample employees),
-- and because every environment must hold the same vocabulary.
--
-- Idempotent: ON CONFLICT DO NOTHING, so re-running changes nothing and a later
-- ZingHR-driven refresh can write to the same table.

-- CreateTable
CREATE TABLE "master_options" (
    "id" TEXT NOT NULL,
    "kind" VARCHAR(20) NOT NULL,
    "value" VARCHAR(200) NOT NULL,
    "parent" VARCHAR(200) NOT NULL DEFAULT '',
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "master_options_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "master_options_kind_parent_idx" ON "master_options"("kind", "parent");

-- CreateIndex
CREATE UNIQUE INDEX "master_options_kind_value_parent_key" ON "master_options"("kind", "value", "parent");

INSERT INTO "master_options" ("id","kind","value","parent","sort_order","updated_at") VALUES
  (gen_random_uuid()::text, 'department', 'Accounts and Finance', '', 0, NOW()),
  (gen_random_uuid()::text, 'department', 'Admin, Safety and Security', '', 1, NOW()),
  (gen_random_uuid()::text, 'department', 'Batching Plant', '', 2, NOW()),
  (gen_random_uuid()::text, 'department', 'Billing', '', 3, NOW()),
  (gen_random_uuid()::text, 'department', 'Board and Company Affairs', '', 4, NOW()),
  (gen_random_uuid()::text, 'department', 'Brand and Communication', '', 5, NOW()),
  (gen_random_uuid()::text, 'department', 'Business Development', '', 6, NOW()),
  (gen_random_uuid()::text, 'department', 'Business Excellence', '', 7, NOW()),
  (gen_random_uuid()::text, 'department', 'Business Operations', '', 8, NOW()),
  (gen_random_uuid()::text, 'department', 'C and F', '', 9, NOW()),
  (gen_random_uuid()::text, 'department', 'CAD', '', 10, NOW()),
  (gen_random_uuid()::text, 'department', 'Central Distribution Center', '', 11, NOW()),
  (gen_random_uuid()::text, 'department', 'Chemical Lab', '', 12, NOW()),
  (gen_random_uuid()::text, 'department', 'Chemical Management', '', 13, NOW()),
  (gen_random_uuid()::text, 'department', 'Commercial', '', 14, NOW()),
  (gen_random_uuid()::text, 'department', 'Communication', '', 15, NOW()),
  (gen_random_uuid()::text, 'department', 'Compliance', '', 16, NOW()),
  (gen_random_uuid()::text, 'department', 'Construction', '', 17, NOW()),
  (gen_random_uuid()::text, 'department', 'Corporate Admin', '', 18, NOW()),
  (gen_random_uuid()::text, 'department', 'Corporate Affairs', '', 19, NOW()),
  (gen_random_uuid()::text, 'department', 'Corporate HR', '', 20, NOW()),
  (gen_random_uuid()::text, 'department', 'Cost and Budget', '', 21, NOW()),
  (gen_random_uuid()::text, 'department', 'Custom Affairs', '', 22, NOW()),
  (gen_random_uuid()::text, 'department', 'Customer Service', '', 23, NOW()),
  (gen_random_uuid()::text, 'department', 'Customer Service and Research', '', 24, NOW()),
  (gen_random_uuid()::text, 'department', 'Cutting', '', 25, NOW()),
  (gen_random_uuid()::text, 'department', 'DBTel', '', 26, NOW()),
  (gen_random_uuid()::text, 'department', 'Design and Development', '', 27, NOW()),
  (gen_random_uuid()::text, 'department', 'Digital', '', 28, NOW()),
  (gen_random_uuid()::text, 'department', 'Director', '', 29, NOW()),
  (gen_random_uuid()::text, 'department', 'Director''s Secretariat', '', 30, NOW()),
  (gen_random_uuid()::text, 'department', 'Distribution', '', 31, NOW()),
  (gen_random_uuid()::text, 'department', 'Dredging', '', 32, NOW()),
  (gen_random_uuid()::text, 'department', 'Dye House', '', 33, NOW()),
  (gen_random_uuid()::text, 'department', 'Dye House Planning and Coordination', '', 34, NOW()),
  (gen_random_uuid()::text, 'department', 'Dyeing', '', 35, NOW()),
  (gen_random_uuid()::text, 'department', 'Dyeing and Finishing', '', 36, NOW()),
  (gen_random_uuid()::text, 'department', 'EHS', '', 37, NOW()),
  (gen_random_uuid()::text, 'department', 'EMS', '', 38, NOW()),
  (gen_random_uuid()::text, 'department', 'Ecommerce', '', 39, NOW()),
  (gen_random_uuid()::text, 'department', 'Engineering', '', 40, NOW()),
  (gen_random_uuid()::text, 'department', 'Enterprise System', '', 41, NOW()),
  (gen_random_uuid()::text, 'department', 'Fabric Development', '', 42, NOW()),
  (gen_random_uuid()::text, 'department', 'Fashion Design and Product Development', '', 43, NOW()),
  (gen_random_uuid()::text, 'department', 'Finance', '', 44, NOW()),
  (gen_random_uuid()::text, 'department', 'Finishing', '', 45, NOW()),
  (gen_random_uuid()::text, 'department', 'Fire and Safety', '', 46, NOW()),
  (gen_random_uuid()::text, 'department', 'GPQ', '', 47, NOW()),
  (gen_random_uuid()::text, 'department', 'Glazing Line and Printing', '', 48, NOW()),
  (gen_random_uuid()::text, 'department', 'Group Finance', '', 49, NOW()),
  (gen_random_uuid()::text, 'department', 'IT Governance', '', 50, NOW()),
  (gen_random_uuid()::text, 'department', 'IT Infrastructure', '', 51, NOW()),
  (gen_random_uuid()::text, 'department', 'IT Infrastructure and Operations', '', 52, NOW()),
  (gen_random_uuid()::text, 'department', 'IT Support', '', 53, NOW()),
  (gen_random_uuid()::text, 'department', 'IT and MIS', '', 54, NOW()),
  (gen_random_uuid()::text, 'department', 'Industrial Engineering', '', 55, NOW()),
  (gen_random_uuid()::text, 'department', 'Installation and Servicing', '', 56, NOW()),
  (gen_random_uuid()::text, 'department', 'Internal Audit', '', 57, NOW()),
  (gen_random_uuid()::text, 'department', 'International Marketing', '', 58, NOW()),
  (gen_random_uuid()::text, 'department', 'Inventory Management', '', 59, NOW()),
  (gen_random_uuid()::text, 'department', 'Lab', '', 60, NOW()),
  (gen_random_uuid()::text, 'department', 'Land and Legal Affairs', '', 61, NOW()),
  (gen_random_uuid()::text, 'department', 'Lean Management', '', 62, NOW()),
  (gen_random_uuid()::text, 'department', 'Logistics', '', 63, NOW()),
  (gen_random_uuid()::text, 'department', 'Logistics and Distribution', '', 64, NOW()),
  (gen_random_uuid()::text, 'department', 'Loss Prevention', '', 65, NOW()),
  (gen_random_uuid()::text, 'department', 'MPD', '', 66, NOW()),
  (gen_random_uuid()::text, 'department', 'Maintenance', '', 67, NOW()),
  (gen_random_uuid()::text, 'department', 'Manufacturing', '', 68, NOW()),
  (gen_random_uuid()::text, 'department', 'Manufacturing Science and Technology', '', 69, NOW()),
  (gen_random_uuid()::text, 'department', 'Market Supply Chain', '', 70, NOW()),
  (gen_random_uuid()::text, 'department', 'Marketing', '', 71, NOW()),
  (gen_random_uuid()::text, 'department', 'Material Management', '', 72, NOW()),
  (gen_random_uuid()::text, 'department', 'Medical', '', 73, NOW()),
  (gen_random_uuid()::text, 'department', 'Medical Affairs', '', 74, NOW()),
  (gen_random_uuid()::text, 'department', 'Medical Services and Training', '', 75, NOW()),
  (gen_random_uuid()::text, 'department', 'Merchandising', '', 76, NOW()),
  (gen_random_uuid()::text, 'department', 'NOC', '', 77, NOW()),
  (gen_random_uuid()::text, 'department', 'Occupational Health and Safety', '', 78, NOW()),
  (gen_random_uuid()::text, 'department', 'Operations', '', 79, NOW()),
  (gen_random_uuid()::text, 'department', 'Operations and Maintenance', '', 80, NOW()),
  (gen_random_uuid()::text, 'department', 'Outlet', '', 81, NOW()),
  (gen_random_uuid()::text, 'department', 'Physical Lab', '', 82, NOW()),
  (gen_random_uuid()::text, 'department', 'Planning', '', 83, NOW()),
  (gen_random_uuid()::text, 'department', 'Planning and Development', '', 84, NOW()),
  (gen_random_uuid()::text, 'department', 'Planning and Implementation', '', 85, NOW()),
  (gen_random_uuid()::text, 'department', 'Plant Admin', '', 86, NOW()),
  (gen_random_uuid()::text, 'department', 'Plant HR', '', 87, NOW()),
  (gen_random_uuid()::text, 'department', 'Pre-Audit', '', 88, NOW()),
  (gen_random_uuid()::text, 'department', 'Process Development', '', 89, NOW()),
  (gen_random_uuid()::text, 'department', 'Procurement', '', 90, NOW()),
  (gen_random_uuid()::text, 'department', 'Production', '', 91, NOW()),
  (gen_random_uuid()::text, 'department', 'Production Coordination', '', 92, NOW()),
  (gen_random_uuid()::text, 'department', 'Production Planning', '', 93, NOW()),
  (gen_random_uuid()::text, 'department', 'Project Planning and Sourcing', '', 94, NOW()),
  (gen_random_uuid()::text, 'department', 'Projects and Customer Success', '', 95, NOW()),
  (gen_random_uuid()::text, 'department', 'Quality', '', 96, NOW()),
  (gen_random_uuid()::text, 'department', 'Quality Assurance', '', 97, NOW()),
  (gen_random_uuid()::text, 'department', 'Quality Control', '', 98, NOW()),
  (gen_random_uuid()::text, 'department', 'Quality Operations', '', 99, NOW()),
  (gen_random_uuid()::text, 'department', 'R and D', '', 100, NOW()),
  (gen_random_uuid()::text, 'department', 'RQS', '', 101, NOW()),
  (gen_random_uuid()::text, 'department', 'Regulatory Affairs', '', 102, NOW()),
  (gen_random_uuid()::text, 'department', 'Regulatory Compliance', '', 103, NOW()),
  (gen_random_uuid()::text, 'department', 'Retail Sales', '', 104, NOW()),
  (gen_random_uuid()::text, 'department', 'SCM', '', 105, NOW()),
  (gen_random_uuid()::text, 'department', 'SCM Planning', '', 106, NOW()),
  (gen_random_uuid()::text, 'department', 'Safety and Security', '', 107, NOW()),
  (gen_random_uuid()::text, 'department', 'Sales', '', 108, NOW()),
  (gen_random_uuid()::text, 'department', 'Sales and Distribution', '', 109, NOW()),
  (gen_random_uuid()::text, 'department', 'Sales and Marketing', '', 110, NOW()),
  (gen_random_uuid()::text, 'department', 'Sample', '', 111, NOW()),
  (gen_random_uuid()::text, 'department', 'Security', '', 112, NOW()),
  (gen_random_uuid()::text, 'department', 'Site Management', '', 113, NOW()),
  (gen_random_uuid()::text, 'department', 'Sorting and Packing', '', 114, NOW()),
  (gen_random_uuid()::text, 'department', 'Sourcing', '', 115, NOW()),
  (gen_random_uuid()::text, 'department', 'Stock', '', 116, NOW()),
  (gen_random_uuid()::text, 'department', 'Stock and Admin', '', 117, NOW()),
  (gen_random_uuid()::text, 'department', 'Store', '', 118, NOW()),
  (gen_random_uuid()::text, 'department', 'Strategic Sourcing', '', 119, NOW()),
  (gen_random_uuid()::text, 'department', 'Sustainability', '', 120, NOW()),
  (gen_random_uuid()::text, 'department', 'TVET', '', 121, NOW()),
  (gen_random_uuid()::text, 'department', 'Technical', '', 122, NOW()),
  (gen_random_uuid()::text, 'department', 'Telecom', '', 123, NOW()),
  (gen_random_uuid()::text, 'department', 'Transport', '', 124, NOW()),
  (gen_random_uuid()::text, 'department', 'Treasury', '', 125, NOW()),
  (gen_random_uuid()::text, 'department', 'Utility', '', 126, NOW()),
  (gen_random_uuid()::text, 'department', 'VTS Monitoring', '', 127, NOW()),
  (gen_random_uuid()::text, 'department', 'Visa Processing and Ticketing', '', 128, NOW()),
  (gen_random_uuid()::text, 'department', 'Warehouse', '', 129, NOW()),
  (gen_random_uuid()::text, 'department', 'Warehouse Logistics and Distributions', '', 130, NOW()),
  (gen_random_uuid()::text, 'department', 'Washing', '', 131, NOW()),
  (gen_random_uuid()::text, 'department', 'Work Study', '', 132, NOW()),
  (gen_random_uuid()::text, 'department', 'Yarn Management', '', 133, NOW()),
  (gen_random_uuid()::text, 'department', 'Yarn and Fibre Procurement', '', 134, NOW()),
  (gen_random_uuid()::text, 'department', 'Zoo', '', 135, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts', 'Accounts and Finance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts Payable', 'Accounts and Finance', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts Receivable', 'Accounts and Finance', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts and Finance', 'Accounts and Finance', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Bank Reconciliation', 'Accounts and Finance', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Billing', 'Accounts and Finance', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Cash Incentive', 'Accounts and Finance', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Commercial', 'Accounts and Finance', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Pre Audit', 'Accounts and Finance', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Credit Control', 'Accounts and Finance', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Export', 'Accounts and Finance', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'Export Billing', 'Accounts and Finance', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'Finance', 'Accounts and Finance', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'Fixed Asset Management', 'Accounts and Finance', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Fund Management', 'Accounts and Finance', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'GL Management', 'Accounts and Finance', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'Import', 'Accounts and Finance', 16, NOW()),
  (gen_random_uuid()::text, 'section', 'PF Management', 'Accounts and Finance', 17, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Accounts', 'Accounts and Finance', 18, NOW()),
  (gen_random_uuid()::text, 'section', 'Tax', 'Accounts and Finance', 19, NOW()),
  (gen_random_uuid()::text, 'section', 'Treasury', 'Accounts and Finance', 20, NOW()),
  (gen_random_uuid()::text, 'section', 'VAT', 'Accounts and Finance', 21, NOW()),
  (gen_random_uuid()::text, 'section', 'Admin, Safety and Security', 'Admin, Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Admin', 'Admin, Safety and Security', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Safety and Security', 'Admin, Safety and Security', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Shared', 'Admin, Safety and Security', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Batching Plant', 'Batching Plant', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Billing Operation', 'Billing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Board Affairs', 'Board and Company Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Shareholder Relation', 'Board and Company Affairs', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Development', 'Brand and Communication', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Communication', 'Brand and Communication', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Agriculture', 'Business Development', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Development', 'Business Development', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Excellence', 'Business Excellence', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Operation', 'Business Operations', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'C and F', 'C and F', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Export and Import', 'C and F', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Site Operations', 'C and F', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'CAD', 'CAD', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Distribution', 'Central Distribution Center', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'General Store', 'Central Distribution Center', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Retail Sales', 'Central Distribution Center', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab', 'Chemical Lab', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Chemical Management', 'Chemical Management', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'C and F', 'Commercial', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Cash Incentive', 'Commercial', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Commercial', 'Commercial', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Customs Bond', 'Commercial', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Customs VAT, BERC, BIDA', 'Commercial', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Customs, City Corporation, BUET', 'Commercial', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Deem Export', 'Commercial', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Deem Export and Import', 'Commercial', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Export', 'Commercial', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Export and Import', 'Commercial', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Import', 'Commercial', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'RMG Customs and Bond', 'Commercial', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'RMG Export', 'Commercial', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'RMG Import', 'Commercial', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Textiles Export', 'Commercial', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'Textiles Import', 'Commercial', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'Communication', 'Communication', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Compliance', 'Compliance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'EMS', 'Compliance', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Social', 'Compliance', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'BOQ and Budgeting', 'Construction', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Billing', 'Construction', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Billing and Documentation', 'Construction', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Civil', 'Construction', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Civil Store', 'Construction', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Construction', 'Construction', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Construction Store', 'Construction', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Design,Buyer Accord,Alliance Related Work', 'Construction', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Electrical', 'Construction', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Electro-Mechanical', 'Construction', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Admin', 'Construction', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'Plumbing Design', 'Construction', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'QC and Safety', 'Construction', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Assurance', 'Construction', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Regulatory Affairs', 'Construction', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'Store', 'Construction', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'Structural Design', 'Construction', 16, NOW()),
  (gen_random_uuid()::text, 'section', 'Structural Drawing', 'Construction', 17, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Admin', 'Corporate Admin', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Front Desk', 'Corporate Admin', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'HR Operations', 'Corporate Admin', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Affairs', 'Corporate Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Admin', 'Corporate HR', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'HR Operations', 'Corporate HR', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Learning and Development', 'Corporate HR', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Talent Acquisition', 'Corporate HR', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Cost and Budget', 'Cost and Budget', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Fabric', 'Cost and Budget', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Accounts', 'Cost and Budget', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Cost and Budget', 'Cost and Budget', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Custom Affairs', 'Custom Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Customer Service', 'Customer Service', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Customer Service', 'Customer Service and Research', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales', 'Customer Service and Research', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Cutting', 'Cutting', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'DBTel Operation', 'DBTel', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'CAD', 'Design and Development', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Design and Development', 'Design and Development', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Print and Embroidery', 'Design and Development', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'ERP Implementation and Support', 'Digital', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Support', 'Digital', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Projects and Customer Success', 'Digital', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Supply Chain', 'Digital', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'System Support', 'Digital', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Director', 'Director', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Public Relations and Protocol', 'Director''s Secretariat', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Secretariat', 'Director''s Secretariat', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Distribution', 'Distribution', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Operations', 'Dredging', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Dye House', 'Dye House', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Dye House Planning and Coordination', 'Dye House Planning and Coordination', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Batching', 'Dyeing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Dyeing', 'Dyeing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Production', 'Dyeing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'R and D', 'Dyeing', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Sample', 'Dyeing', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Sub Contract Coordination', 'Dyeing', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Dyeing and Finishing', 'Dyeing and Finishing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'EHS', 'EHS', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'ETP', 'EMS', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Ecommerce', 'Ecommerce', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Marketing', 'Ecommerce', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Engineering', 'Engineering', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Process', 'Engineering', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Utility', 'Engineering', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Development', 'Enterprise System', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Software Development', 'Enterprise System', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'System Implementation', 'Enterprise System', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'System Lifecycle Management', 'Enterprise System', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'System Operations', 'Enterprise System', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'System Support', 'Enterprise System', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Fabric Development', 'Fabric Development', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales and Marketing', 'Fabric Development', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Fashion Design and Product Development', 'Fashion Design and Product Development', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts and Finance', 'Finance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Batching', 'Finishing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Cone Winding', 'Finishing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Finishing', 'Finishing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Fire and Safety', 'Fire and Safety', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Bestseller', 'GPQ', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'C and A', 'GPQ', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'G-STAR', 'GPQ', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'GPQ', 'GPQ', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'GUESS', 'GPQ', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'George', 'GPQ', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'H and M', 'GPQ', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Hugo Boss', 'GPQ', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Hugo Boss, Esprit', 'GPQ', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'K-Mart', 'GPQ', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Lasenza', 'GPQ', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'M and S', 'GPQ', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'New Frontier', 'GPQ', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'Next', 'GPQ', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Puma', 'GPQ', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality', 'GPQ', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'VF ASIA', 'GPQ', 16, NOW()),
  (gen_random_uuid()::text, 'section', 'Walmart', 'GPQ', 17, NOW()),
  (gen_random_uuid()::text, 'section', 'ZARA', 'GPQ', 18, NOW()),
  (gen_random_uuid()::text, 'section', 'Glazing Line and Printing', 'Glazing Line and Printing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts and Finance', 'Group Finance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Information Security', 'IT Governance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Project Management', 'IT Governance', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Infrastructure', 'IT Infrastructure', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Infrastructure and Operations', 'IT Infrastructure', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Operations', 'IT Infrastructure', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Operations Management', 'IT Infrastructure', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Planning and Operations', 'IT Infrastructure', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Support', 'IT Infrastructure', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'IT and Telecom Support', 'IT Infrastructure', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'System Operations', 'IT Infrastructure', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Infrastructure', 'IT Infrastructure and Operations', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Planning and Operations', 'IT Infrastructure and Operations', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Operations', 'IT Support', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Support', 'IT Support', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant IT Support', 'IT Support', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Application Support', 'IT and MIS', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Operation', 'IT and MIS', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'ERP Implementation and Support', 'IT and MIS', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Infrastructure', 'IT and MIS', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'IT Support', 'IT and MIS', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Process Development', 'IT and MIS', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Industrial Engineering', 'Industrial Engineering', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Work Study', 'Industrial Engineering', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'CCTV Systems', 'Installation and Servicing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'DBL Distribution Ltd', 'Installation and Servicing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Fire Alarm and Safety System', 'Installation and Servicing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Inkcups - Tagless Printing', 'Installation and Servicing', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Lift Installation and Servicing', 'Installation and Servicing', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Finance', 'Internal Audit', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Internal Audit', 'Internal Audit', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'International Marketing', 'International Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Chemical', 'Inventory Management', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Fabric', 'Inventory Management', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Inventory', 'Inventory Management', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Analytical Lab', 'Lab', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Chemical Lab', 'Lab', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Dye House Lab', 'Lab', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Dyeing Lab', 'Lab', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Lab', 'Lab', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab', 'Lab', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab Ext', 'Lab', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab H and M', 'Lab', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Washing Lab', 'Lab', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Land', 'Land and Legal Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Land and Legal Affairs', 'Land and Legal Affairs', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Legal and Banking', 'Land and Legal Affairs', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Lean Management', 'Lean Management', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Admin', 'Logistics', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Log In', 'Logistics', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Logistics', 'Logistics', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Store', 'Logistics', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Logistics and Distribution', 'Logistics and Distribution', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Loss Prevention', 'Loss Prevention', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'CAD', 'MPD', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'MPD', 'MPD', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'ETP', 'Maintenance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Electrical', 'Maintenance', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Generator', 'Maintenance', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Glazing Line and Printing', 'Maintenance', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Maintenance', 'Maintenance', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Mechanical', 'Maintenance', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Press and Dryer', 'Maintenance', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Utility', 'Maintenance', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Manufacturing', 'Manufacturing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Process Support', 'Manufacturing Science and Technology', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Distribution', 'Market Supply Chain', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Market Supply Chain', 'Market Supply Chain', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'ATL Marketing', 'Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'BTL Marketing', 'Marketing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Operation', 'Marketing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Creative Service', 'Marketing', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Marketing', 'Marketing', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Printing', 'Marketing', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales', 'Marketing', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Yarn Marketing', 'Marketing', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Supply Chain', 'Material Management', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Medical', 'Medical', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Medical', 'Medical Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Medical Services and Training', 'Medical Services and Training', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Bestseller', 'Merchandising', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Bonita', 'Merchandising', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'C and A', 'Merchandising', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Camel Active', 'Merchandising', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Dickeis', 'Merchandising', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Esprit', 'Merchandising', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'G-STAR', 'Merchandising', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'G-STAT, CARTERS, MQ, NEW FONTIER', 'Merchandising', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'GUESS', 'Merchandising', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'George', 'Merchandising', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'H and M', 'Merchandising', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'Hugo Boss', 'Merchandising', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'Justice', 'Merchandising', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'K-Mart', 'Merchandising', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Lasenza', 'Merchandising', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'M and S', 'Merchandising', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'Merchandising', 'Merchandising', 16, NOW()),
  (gen_random_uuid()::text, 'section', 'New Frontier', 'Merchandising', 17, NOW()),
  (gen_random_uuid()::text, 'section', 'Next', 'Merchandising', 18, NOW()),
  (gen_random_uuid()::text, 'section', 'Puma', 'Merchandising', 19, NOW()),
  (gen_random_uuid()::text, 'section', 'Ralph Lauren', 'Merchandising', 20, NOW()),
  (gen_random_uuid()::text, 'section', 'Target Australia', 'Merchandising', 21, NOW()),
  (gen_random_uuid()::text, 'section', 'The North Face', 'Merchandising', 22, NOW()),
  (gen_random_uuid()::text, 'section', 'Tom Tailor', 'Merchandising', 23, NOW()),
  (gen_random_uuid()::text, 'section', 'VF ASIA', 'Merchandising', 24, NOW()),
  (gen_random_uuid()::text, 'section', 'Vouge Sourcing', 'Merchandising', 25, NOW()),
  (gen_random_uuid()::text, 'section', 'Walmart', 'Merchandising', 26, NOW()),
  (gen_random_uuid()::text, 'section', 'ZARA', 'Merchandising', 27, NOW()),
  (gen_random_uuid()::text, 'section', 'Zara Women', 'Merchandising', 28, NOW()),
  (gen_random_uuid()::text, 'section', 'Telecom NOC', 'NOC', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Occupational Health and Safety', 'Occupational Health and Safety', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Development', 'Operations', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Cargo Operations', 'Operations', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'DBL Distribution Ltd', 'Operations', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Operations', 'Operations', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning', 'Operations', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Production', 'Operations', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Civil', 'Operations and Maintenance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Dredger', 'Operations and Maintenance', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Dredging', 'Operations and Maintenance', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Mechanical', 'Operations and Maintenance', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Operations', 'Operations and Maintenance', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Project Operations', 'Operations and Maintenance', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Site Operations', 'Operations and Maintenance', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Puma Chittagong', 'Outlet', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab', 'Physical Lab', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab Ext', 'Physical Lab', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Physical Lab H and M', 'Physical Lab', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning', 'Planning', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Production Planning', 'Planning', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Dredging', 'Planning and Development', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning', 'Planning and Implementation', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning and Implementation', 'Planning and Implementation', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Admin, Safety and Security', 'Plant Admin', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Admin', 'Plant Admin', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Admin', 'Plant Admin', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Shipment', 'Plant Admin', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Transport', 'Plant Admin', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Waste Disposal', 'Plant Admin', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'HR Operations', 'Plant HR', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Welfare', 'Plant HR', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Pre Audit', 'Pre-Audit', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Group Finance-Internal Audit', 'Pre-Audit', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Plant Pre-Audit', 'Pre-Audit', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Process Development', 'Process Development', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Procurement', 'Procurement', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Sourcing', 'Procurement', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Yarn', 'Procurement', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Batching', 'Production', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Body Preparation', 'Production', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Color Kitchen', 'Production', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Cutting', 'Production', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Decoration', 'Production', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Design', 'Production', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Design and Development', 'Production', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Dye House', 'Production', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Dyeing', 'Production', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Embroidery', 'Production', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Engraving', 'Production', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'Finishing', 'Production', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'Glazing Line and Printing', 'Production', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'Industrial Engineering', 'Production', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Kiln and Intermediate Storages', 'Production', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'Knitting', 'Production', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'Lab', 'Production', 16, NOW()),
  (gen_random_uuid()::text, 'section', 'Lab and Glaze Preparation', 'Production', 17, NOW()),
  (gen_random_uuid()::text, 'section', 'Lean Management', 'Production', 18, NOW()),
  (gen_random_uuid()::text, 'section', 'Packing', 'Production', 19, NOW()),
  (gen_random_uuid()::text, 'section', 'Polishing and Squaring', 'Production', 20, NOW()),
  (gen_random_uuid()::text, 'section', 'Pre Production', 'Production', 21, NOW()),
  (gen_random_uuid()::text, 'section', 'Press and Dryer', 'Production', 22, NOW()),
  (gen_random_uuid()::text, 'section', 'Print and Embroidery', 'Production', 23, NOW()),
  (gen_random_uuid()::text, 'section', 'Printing', 'Production', 24, NOW()),
  (gen_random_uuid()::text, 'section', 'Printing and Color Kitchen', 'Production', 25, NOW()),
  (gen_random_uuid()::text, 'section', 'Process Development', 'Production', 26, NOW()),
  (gen_random_uuid()::text, 'section', 'Production', 'Production', 27, NOW()),
  (gen_random_uuid()::text, 'section', 'Production Planning', 'Production', 28, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Control', 'Production', 29, NOW()),
  (gen_random_uuid()::text, 'section', 'R and D', 'Production', 30, NOW()),
  (gen_random_uuid()::text, 'section', 'Ring', 'Production', 31, NOW()),
  (gen_random_uuid()::text, 'section', 'Rotor', 'Production', 32, NOW()),
  (gen_random_uuid()::text, 'section', 'Sample', 'Production', 33, NOW()),
  (gen_random_uuid()::text, 'section', 'Sample Development', 'Production', 34, NOW()),
  (gen_random_uuid()::text, 'section', 'Sewing', 'Production', 35, NOW()),
  (gen_random_uuid()::text, 'section', 'Sorting and Packing', 'Production', 36, NOW()),
  (gen_random_uuid()::text, 'section', 'Embroidery', 'Production Coordination', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Knitting', 'Production Coordination', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Production Coordination', 'Production Coordination', 2, NOW()),
  (gen_random_uuid()::text, 'section', '3rd Party Production Planning', 'Production Planning', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Civil Store', 'Production Planning', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Fabric', 'Production Planning', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning', 'Production Planning', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning and Implementation', 'Production Planning', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Production', 'Production Planning', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Production Planning', 'Production Planning', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning and Implementation', 'Project Planning and Sourcing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Project Management', 'Projects and Customer Success', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Cutting', 'Quality', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Printing', 'Quality', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Production', 'Quality', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality', 'Quality', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Shade', 'Quality', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Assurance', 'Quality Assurance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Knitting', 'Quality Control', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Process Development', 'Quality Control', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality', 'Quality Control', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Control', 'Quality Control', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Operation', 'Quality Control', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Sample Development', 'Quality Control', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Sewing', 'Quality Control', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Microbiology', 'Quality Operations', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Assurance', 'Quality Operations', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Control', 'Quality Operations', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality Operation', 'Quality Operations', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Validation', 'Quality Operations', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Analytical Development', 'R and D', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Application Development', 'R and D', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Formulation Development', 'R and D', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Knitting', 'R and D', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'R and D', 'R and D', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'C and A', 'RQS', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'H and M', 'RQS', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'K-Mart', 'RQS', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'RQS', 'RQS', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Regulatory Affairs', 'Regulatory Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Compliance', 'Regulatory Compliance', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Adidas Gulshan', 'Retail Sales', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Puma Dhanmondi', 'Retail Sales', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Retail Sales', 'Retail Sales', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales', 'Retail Sales', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Bond', 'SCM', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Customer Service', 'SCM', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Demand Planning', 'SCM', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Logistics', 'SCM', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Planning', 'SCM', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Procurement', 'SCM', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'SCM Planning', 'SCM', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Supply Chain', 'SCM', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'SCM Planning', 'SCM Planning', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Supply Chain', 'SCM Planning', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'CCTV', 'Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Fire and Safety', 'Safety and Security', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Safety and Security', 'Safety and Security', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Security', 'Safety and Security', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Business Operation', 'Sales', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Ceramic Sales', 'Sales', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Admin', 'Sales', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Corporate Sales', 'Sales', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Dealer Sales', 'Sales', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Display Center', 'Sales', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Distribution', 'Sales', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Puma Banani', 'Sales', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Retail Sales', 'Sales', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales', 'Sales', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales and Marketing', 'Sales', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'Distribution', 'Sales and Distribution', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales', 'Sales and Distribution', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Credit Control', 'Sales and Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Fabric', 'Sales and Marketing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Inkcups - Tagless Printing', 'Sales and Marketing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Marketing', 'Sales and Marketing', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales', 'Sales and Marketing', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Sales and Marketing', 'Sales and Marketing', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Technical Sales', 'Sales and Marketing', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Embroidery', 'Sample', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'GPQ', 'Sample', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality', 'Sample', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Sample', 'Sample', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Bestseller', 'Security', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Fire and Safety', 'Security', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Safety and Security', 'Security', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Security', 'Security', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Operational Excellence', 'Site Management', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Site Management', 'Site Management', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Site Operations', 'Site Management', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Sorting and Packing', 'Sorting and Packing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Accessories', 'Sourcing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Procurement', 'Sourcing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Sourcing', 'Sourcing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Stock', 'Stock', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Warehouse', 'Stock', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Shared', 'Stock and Admin', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Stock', 'Stock and Admin', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Accessories', 'Store', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Accessories Store', 'Store', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Bhuyan Bari Store', 'Store', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Chemical', 'Store', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Chemical Store', 'Store', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Fabric Store', 'Store', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Finish Fabric Store', 'Store', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'General Store', 'Store', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'Grey Store', 'Store', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Inventory', 'Store', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Maintenance Store', 'Store', 10, NOW()),
  (gen_random_uuid()::text, 'section', 'Sample Store', 'Store', 11, NOW()),
  (gen_random_uuid()::text, 'section', 'Spare Parts and General Store', 'Store', 12, NOW()),
  (gen_random_uuid()::text, 'section', 'Store', 'Store', 13, NOW()),
  (gen_random_uuid()::text, 'section', 'Washing Fabrics Store', 'Store', 14, NOW()),
  (gen_random_uuid()::text, 'section', 'Yarn Store', 'Store', 15, NOW()),
  (gen_random_uuid()::text, 'section', 'Procurement', 'Strategic Sourcing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Strategic Sourcing', 'Strategic Sourcing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Sustainability', 'Sustainability', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'TVET', 'TVET', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Embroidery', 'Technical', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Knitting', 'Technical', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Technical', 'Technical', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Billing', 'Telecom', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Transport', 'Transport', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Accounts and Finance', 'Treasury', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Fund Management', 'Treasury', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Electric and Electronics', 'Utility', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Electrical', 'Utility', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Generator', 'Utility', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'Generator and Co-Generation System', 'Utility', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Knitting', 'Utility', 4, NOW()),
  (gen_random_uuid()::text, 'section', 'Maintenance', 'Utility', 5, NOW()),
  (gen_random_uuid()::text, 'section', 'Mechanical', 'Utility', 6, NOW()),
  (gen_random_uuid()::text, 'section', 'Utility', 'Utility', 7, NOW()),
  (gen_random_uuid()::text, 'section', 'WTP, Compressor and Fire Hydrant', 'Utility', 8, NOW()),
  (gen_random_uuid()::text, 'section', 'Workshop', 'Utility', 9, NOW()),
  (gen_random_uuid()::text, 'section', 'Accessories Store', 'VTS Monitoring', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Security', 'VTS Monitoring', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Visa Processing', 'Visa Processing and Ticketing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Warehouse', 'Warehouse', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Warehouse', 'Warehouse Logistics and Distributions', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Denim', 'Washing', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Production', 'Washing', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Quality', 'Washing', 2, NOW()),
  (gen_random_uuid()::text, 'section', 'R and D', 'Washing', 3, NOW()),
  (gen_random_uuid()::text, 'section', 'Lean Management', 'Work Study', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Work Study', 'Work Study', 1, NOW()),
  (gen_random_uuid()::text, 'section', 'Yarn Management', 'Yarn Management', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Procurement', 'Yarn and Fibre Procurement', 0, NOW()),
  (gen_random_uuid()::text, 'section', 'Zoo', 'Zoo', 0, NOW()),
  (gen_random_uuid()::text, 'designation', 'Additional General Manager', '', 0, NOW()),
  (gen_random_uuid()::text, 'designation', 'Architect', '', 1, NOW()),
  (gen_random_uuid()::text, 'designation', 'Area Manager', '', 2, NOW()),
  (gen_random_uuid()::text, 'designation', 'Area Manager of PUMA', '', 3, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Engineer', '', 4, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Executive', '', 5, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant General Manager', '', 6, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Manager', '', 7, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Merchandiser', '', 8, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Officer', '', 9, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Secretary', '', 10, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant Security Officer', '', 11, NOW()),
  (gen_random_uuid()::text, 'designation', 'Assistant System Engineer', '', 12, NOW()),
  (gen_random_uuid()::text, 'designation', 'Associate', '', 13, NOW()),
  (gen_random_uuid()::text, 'designation', 'Associate I', '', 14, NOW()),
  (gen_random_uuid()::text, 'designation', 'Associate II', '', 15, NOW()),
  (gen_random_uuid()::text, 'designation', 'Board of Director', '', 16, NOW()),
  (gen_random_uuid()::text, 'designation', 'Brand Executive', '', 17, NOW()),
  (gen_random_uuid()::text, 'designation', 'Business Development Manager', '', 18, NOW()),
  (gen_random_uuid()::text, 'designation', 'Business Development Specialist', '', 19, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chairman', '', 20, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Business Officer', '', 21, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Engineer', '', 22, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Executive Officer', '', 23, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Financial Officer', '', 24, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Human Resources Officer', '', 25, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Information Officer', '', 26, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Internal Audit Officer', '', 27, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Marketing Officer', '', 28, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Medical Officer', '', 29, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Operating Officer', '', 30, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Operation Officer', '', 31, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Production Officer', '', 32, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Risk Officer', '', 33, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Security and Governance Officer', '', 34, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Supply Chain Officer', '', 35, NOW()),
  (gen_random_uuid()::text, 'designation', 'Chief Sustainability Officer', '', 36, NOW()),
  (gen_random_uuid()::text, 'designation', 'Communication Specialist', '', 37, NOW()),
  (gen_random_uuid()::text, 'designation', 'Construction Supervising Engineer', '', 38, NOW()),
  (gen_random_uuid()::text, 'designation', 'Consultant', '', 39, NOW()),
  (gen_random_uuid()::text, 'designation', 'Coordinator', '', 40, NOW()),
  (gen_random_uuid()::text, 'designation', 'Deputy General Manager', '', 41, NOW()),
  (gen_random_uuid()::text, 'designation', 'Deputy Manager', '', 42, NOW()),
  (gen_random_uuid()::text, 'designation', 'Deputy Managing Director', '', 43, NOW()),
  (gen_random_uuid()::text, 'designation', 'Deputy Secretary', '', 44, NOW()),
  (gen_random_uuid()::text, 'designation', 'Designer', '', 45, NOW()),
  (gen_random_uuid()::text, 'designation', 'Director', '', 46, NOW()),
  (gen_random_uuid()::text, 'designation', 'Dredger Engineer', '', 47, NOW()),
  (gen_random_uuid()::text, 'designation', 'Engineer', '', 48, NOW()),
  (gen_random_uuid()::text, 'designation', 'Executive', '', 49, NOW()),
  (gen_random_uuid()::text, 'designation', 'Executive Assistant', '', 50, NOW()),
  (gen_random_uuid()::text, 'designation', 'Executive Director', '', 51, NOW()),
  (gen_random_uuid()::text, 'designation', 'Executive I', '', 52, NOW()),
  (gen_random_uuid()::text, 'designation', 'Executive II', '', 53, NOW()),
  (gen_random_uuid()::text, 'designation', 'Factory Manager', '', 54, NOW()),
  (gen_random_uuid()::text, 'designation', 'Fashion Designer', '', 55, NOW()),
  (gen_random_uuid()::text, 'designation', 'Finance Controller', '', 56, NOW()),
  (gen_random_uuid()::text, 'designation', 'Functional Analyst', '', 57, NOW()),
  (gen_random_uuid()::text, 'designation', 'General Manager', '', 58, NOW()),
  (gen_random_uuid()::text, 'designation', 'Graphics Designer', '', 59, NOW()),
  (gen_random_uuid()::text, 'designation', 'Group Chief Financial Officer', '', 60, NOW()),
  (gen_random_uuid()::text, 'designation', 'Group Head', '', 61, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head', '', 62, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of C and F Operations', '', 63, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Construction', '', 64, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Design and Development', '', 65, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Engineering', '', 66, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Fashion Design and Product Development', '', 67, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Human Resources', '', 68, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of IT', '', 69, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Marketing', '', 70, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Operation', '', 71, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Procurement', '', 72, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Quality Operations', '', 73, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of RandD', '', 74, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Sales', '', 75, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Sales and Marketing', '', 76, NOW()),
  (gen_random_uuid()::text, 'designation', 'Head of Supply Chain', '', 77, NOW()),
  (gen_random_uuid()::text, 'designation', 'In-charge Financial Control', '', 78, NOW()),
  (gen_random_uuid()::text, 'designation', 'Independent Director', '', 79, NOW()),
  (gen_random_uuid()::text, 'designation', 'Intern', '', 80, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Designer', '', 81, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Engineer', '', 82, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Executive', '', 83, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Fashion Designer', '', 84, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Functional Analyst', '', 85, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Graphics Designer', '', 86, NOW()),
  (gen_random_uuid()::text, 'designation', 'Junior Officer', '', 87, NOW()),
  (gen_random_uuid()::text, 'designation', 'Lead Architect', '', 88, NOW()),
  (gen_random_uuid()::text, 'designation', 'Lead, Credit Control', '', 89, NOW()),
  (gen_random_uuid()::text, 'designation', 'Lead, Plant Accounts', '', 90, NOW()),
  (gen_random_uuid()::text, 'designation', 'Lead, Plant Logistics', '', 91, NOW()),
  (gen_random_uuid()::text, 'designation', 'Lead, SCP', '', 92, NOW()),
  (gen_random_uuid()::text, 'designation', 'Management Trainee Officer', '', 93, NOW()),
  (gen_random_uuid()::text, 'designation', 'Manager', '', 94, NOW()),
  (gen_random_uuid()::text, 'designation', 'Managing Director', '', 95, NOW()),
  (gen_random_uuid()::text, 'designation', 'Medical Officer', '', 96, NOW()),
  (gen_random_uuid()::text, 'designation', 'Merchandiser', '', 97, NOW()),
  (gen_random_uuid()::text, 'designation', 'Officer', '', 98, NOW()),
  (gen_random_uuid()::text, 'designation', 'Oracle NetSuite Specialist', '', 99, NOW()),
  (gen_random_uuid()::text, 'designation', 'Outlet In-Charge', '', 100, NOW()),
  (gen_random_uuid()::text, 'designation', 'Portfolio Executive', '', 101, NOW()),
  (gen_random_uuid()::text, 'designation', 'Portfolio Manager', '', 102, NOW()),
  (gen_random_uuid()::text, 'designation', 'Product Associate', '', 103, NOW()),
  (gen_random_uuid()::text, 'designation', 'Product Developer', '', 104, NOW()),
  (gen_random_uuid()::text, 'designation', 'Product Executive', '', 105, NOW()),
  (gen_random_uuid()::text, 'designation', 'Product Manager', '', 106, NOW()),
  (gen_random_uuid()::text, 'designation', 'Programmer', '', 107, NOW()),
  (gen_random_uuid()::text, 'designation', 'Project Engineer', '', 108, NOW()),
  (gen_random_uuid()::text, 'designation', 'Psychologist', '', 109, NOW()),
  (gen_random_uuid()::text, 'designation', 'Regional Manager', '', 110, NOW()),
  (gen_random_uuid()::text, 'designation', 'Regional Sales Manager', '', 111, NOW()),
  (gen_random_uuid()::text, 'designation', 'Research Executive', '', 112, NOW()),
  (gen_random_uuid()::text, 'designation', 'Sales Associate', '', 113, NOW()),
  (gen_random_uuid()::text, 'designation', 'Scientific Information Executive', '', 114, NOW()),
  (gen_random_uuid()::text, 'designation', 'Scientific Information Officer', '', 115, NOW()),
  (gen_random_uuid()::text, 'designation', 'Secretary', '', 116, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Area Manager', '', 117, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Associate', '', 118, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Brand Executive', '', 119, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Brand Manager', '', 120, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Engineer', '', 121, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Executive', '', 122, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Fashion Designer', '', 123, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior General Manager', '', 124, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Graphic Designer', '', 125, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Manager', '', 126, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Marketing Manager', '', 127, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Medical Officer', '', 128, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Merchandiser', '', 129, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Officer', '', 130, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Portfolio Executive', '', 131, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Portfolio Manager', '', 132, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Product Executive', '', 133, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Product Manager', '', 134, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Programmer', '', 135, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Project Engineer', '', 136, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Regional Manager', '', 137, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Scientific Information Officer', '', 138, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Software Engineer', '', 139, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior System Engineer', '', 140, NOW()),
  (gen_random_uuid()::text, 'designation', 'Senior Territory Officer', '', 141, NOW()),
  (gen_random_uuid()::text, 'designation', 'Site Engineer', '', 142, NOW()),
  (gen_random_uuid()::text, 'designation', 'Site Head', '', 143, NOW()),
  (gen_random_uuid()::text, 'designation', 'Software Engineer', '', 144, NOW()),
  (gen_random_uuid()::text, 'designation', 'System Engineer', '', 145, NOW()),
  (gen_random_uuid()::text, 'designation', 'Technical Assistant Officer', '', 146, NOW()),
  (gen_random_uuid()::text, 'designation', 'Technical Expert', '', 147, NOW()),
  (gen_random_uuid()::text, 'designation', 'Territory Executive', '', 148, NOW()),
  (gen_random_uuid()::text, 'designation', 'Territory Officer', '', 149, NOW()),
  (gen_random_uuid()::text, 'designation', 'Territory Sales Manager', '', 150, NOW()),
  (gen_random_uuid()::text, 'designation', 'Vice Chairman', '', 151, NOW()),
  (gen_random_uuid()::text, 'designation', 'Zonal Manager', '', 152, NOW()),
  (gen_random_uuid()::text, 'designation', 'Zonal Sales Manager', '', 153, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM3', 'Additional General Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Architect', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Architect', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Area Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Area Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Area Manager of PUMA', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Assistant Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Assistant Engineer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Assistant Engineer', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Assistant Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M8', 'Assistant General Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Assistant General Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Assistant General Manager', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Assistant Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Assistant Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Assistant Manager', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Assistant Merchandiser', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Assistant Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Assistant Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Assistant Secretary', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Assistant Security Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Assistant System Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T1', 'Associate', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T1', 'Associate I', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Associate II', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'BM2', 'Board of Director', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Brand Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Business Development Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Business Development Specialist', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'BM2', 'Chairman', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Business Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M15', 'Chief Executive Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM2', 'Chief Executive Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M10', 'Chief Financial Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM3', 'Chief Financial Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Chief Financial Officer', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM5', 'Chief Financial Officer', 3, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Human Resources Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Information Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Chief Internal Audit Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M12', 'Chief Marketing Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Chief Medical Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Operating Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM1', 'Chief Operating Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Operation Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Production Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Chief Risk Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Security and Governance Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M11', 'Chief Supply Chain Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM5', 'Chief Supply Chain Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Chief Sustainability Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Communication Specialist', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Construction Supervising Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Consultant', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Coordinator', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M9', 'Deputy General Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Deputy General Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM3', 'Deputy General Manager', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Deputy Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'BM2', 'Deputy Managing Director', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Deputy Secretary', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM2', 'Director', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Dredger Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Engineer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Engineer', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Executive', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Executive', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Executive Assistant', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M13', 'Executive Director', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM1', 'Executive Director', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM2', 'Executive Director', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Executive I', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Executive I', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Executive II', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Executive II', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Executive II', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Factory Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Fashion Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Finance Controller', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM3', 'Finance Controller', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Functional Analyst', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M11', 'General Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'General Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM5', 'General Manager', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Graphics Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM1', 'Group Chief Financial Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Group Head', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Head', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Head', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Head of C and F Operations', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Head of C and F Operations', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM6', 'Head of Construction', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Head of Design and Development', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Head of Engineering', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM3', 'Head of Fashion Design and Product Development', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM5', 'Head of Human Resources', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Head of IT', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Head of Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Head of Operation', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Head of Operation', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM3', 'Head of Procurement', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Head of Quality Operations', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Head of Quality Operations', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Head of RandD', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Head of RandD', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Head of Sales', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Head of Sales', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Head of Sales', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Head of Sales and Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M11', 'Head of Supply Chain', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'In-charge Financial Control', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM2', 'Independent Director', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Intern', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Fashion Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Functional Analyst', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Graphics Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Junior Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Lead Architect', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Lead, Credit Control', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Lead, Plant Accounts', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Lead, Plant Logistics', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Lead, SCP', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Management Trainee Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Management Trainee Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'BM2', 'Managing Director', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Medical Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Medical Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Medical Officer', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Merchandiser', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Oracle NetSuite Specialist', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Outlet In-Charge', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Outlet In-Charge', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Portfolio Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Portfolio Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T1', 'Product Associate', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Product Developer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Product Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Product Executive', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M6', 'Product Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Programmer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Project Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Project Engineer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Project Engineer', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Psychologist', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Regional Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Regional Sales Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Research Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Sales Associate', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Scientific Information Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T1', 'Scientific Information Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM2', 'Secretary', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Area Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Senior Associate', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Brand Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Senior Brand Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Senior Engineer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Senior Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Executive', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Senior Executive', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Fashion Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM5', 'Senior General Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Graphic Designer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Senior Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM1', 'Senior Manager', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Senior Marketing Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M7', 'Senior Medical Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Merchandiser', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Senior Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Senior Officer', 2, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Portfolio Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Senior Portfolio Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Product Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Senior Product Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Programmer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Senior Programmer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Project Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Senior Regional Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Senior Scientific Information Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior Software Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M3', 'Senior System Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T1', 'Senior Territory Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Senior Territory Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Site Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Site Engineer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'TM1', 'Site Head', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'Software Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M2', 'System Engineer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Technical Assistant Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'SM4', 'Technical Expert', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Territory Executive', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M1', 'Territory Executive', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'T1', 'Territory Officer', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'T2', 'Territory Officer', 1, NOW()),
  (gen_random_uuid()::text, 'grade', 'M5', 'Territory Sales Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'BM2', 'Vice Chairman', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Zonal Manager', 0, NOW()),
  (gen_random_uuid()::text, 'grade', 'M4', 'Zonal Sales Manager', 0, NOW()),
  (gen_random_uuid()::text, 'zone', 'Dhaka Zone', '', 0, NOW()),
  (gen_random_uuid()::text, 'zone', 'Kashimpur Zone', '', 1, NOW()),
  (gen_random_uuid()::text, 'zone', 'Mawna Zone', '', 2, NOW()),
  (gen_random_uuid()::text, 'zone', 'Pharma Zone', '', 3, NOW()),
  (gen_random_uuid()::text, 'zone', 'Sylhet Zone', '', 4, NOW())
ON CONFLICT ("kind","value","parent") DO NOTHING;
