import {
  AUTOMATED_EMAIL_NOTICE,
  EMAIL_LOGO_CID,
  finaliseOutgoing,
  hasAutomatedNotice,
  previewHtml,
  withAutomatedNotice,
} from './automated-notice';

const count = (haystack: string, needle: string) =>
  haystack.split(needle).length - 1;

describe('withAutomatedNotice — every message ends with it', () => {
  it('adds it to a plain-text message, after a rule', () => {
    const out = withAutomatedNotice({ text: 'Dear Rahim,\n\nHello.\n' });
    expect(out.text).toBe(
      `Dear Rahim,\n\nHello.\n\n—\n${AUTOMATED_EMAIL_NOTICE}`,
    );
  });

  it('puts it just inside </body> of a whole document', () => {
    const out = withAutomatedNotice({
      html: '<!doctype html><html><body><p>Hi</p></body></html>',
    });
    expect(out.html).toMatch(
      new RegExp(
        `<p>Hi</p><div[^>]*>${AUTOMATED_EMAIL_NOTICE}</div>\\n</body></html>$`,
      ),
    );
  });

  it('appends it to a fragment', () => {
    const out = withAutomatedNotice({ html: '<div>Your code is 123456</div>' });
    expect(out.html?.startsWith('<div>Your code is 123456</div>')).toBe(true);
    expect(out.html?.endsWith(`${AUTOMATED_EMAIL_NOTICE}</div>`)).toBe(true);
  });

  it('goes at the very end when more follows the document (the inline offer letter)', () => {
    const html =
      '<html><body>Covering note</body></html><hr><div>The letter</div>';
    const out = withAutomatedNotice({ html });
    expect(out.html?.indexOf(AUTOMATED_EMAIL_NOTICE)).toBeGreaterThan(
      out.html!.indexOf('The letter'),
    );
  });

  it('never adds it twice', () => {
    const once = withAutomatedNotice({ text: 'Hi', html: '<p>Hi</p>' });
    const twice = withAutomatedNotice(once);
    expect(twice).toEqual(once);
    expect(count(twice.text!, AUTOMATED_EMAIL_NOTICE)).toBe(1);
    expect(count(twice.html!, AUTOMATED_EMAIL_NOTICE)).toBe(1);
  });

  it('recognises it set on two lines, and does not add a second', () => {
    const html =
      '<td>This is an automated email generated by the DBL Group Recruitment System.<br>Please do not reply to this email.</td>';
    expect(hasAutomatedNotice(html)).toBe(true);
    expect(withAutomatedNotice({ html }).html).toBe(html);
  });

  it('leaves out a version the message does not have', () => {
    expect(withAutomatedNotice({ text: 'Hi' }).html).toBeUndefined();
    expect(withAutomatedNotice({ html: '<p>Hi</p>' }).text).toBeUndefined();
  });
});

describe('finaliseOutgoing — the logo', () => {
  it('travels with a message that shows it, as an inline image', () => {
    const out = finaliseOutgoing({ html: `<img src="cid:${EMAIL_LOGO_CID}">` });
    expect(out.attachments).toHaveLength(1);
    expect(out.attachments![0]).toMatchObject({
      cid: EMAIL_LOGO_CID,
      contentType: 'image/png',
    });
    // A real PNG, not an empty buffer.
    expect(out.attachments![0].content.subarray(1, 4).toString()).toBe('PNG');
  });

  it('is not attached to a message that does not show it', () => {
    expect(finaliseOutgoing({ html: '<p>Hi</p>' }).attachments).toBeUndefined();
  });

  it('keeps the message’s own attachments, and is attached once', () => {
    const pdf = { filename: 'Offer.pdf', content: Buffer.from('%PDF') };
    const out = finaliseOutgoing({
      html: `<img src="cid:${EMAIL_LOGO_CID}">`,
      attachments: [pdf],
    });
    expect(out.attachments?.map((a) => a.filename)).toEqual([
      'Offer.pdf',
      'dbl-group-logo.png',
    ]);
    expect(finaliseOutgoing(out).attachments).toHaveLength(2);
  });

  it('is inlined for the dev outbox, where cid: resolves to nothing', () => {
    const html = previewHtml(`<img src="cid:${EMAIL_LOGO_CID}">`);
    expect(html).toMatch(/^<img src="data:image\/png;base64,iVBOR/);
  });
});
