import { EMAIL_LOGO_PNG_BASE64 } from './email-logo';

/**
 * What every email the system sends says at the bottom.
 *
 * MailService puts it on each message on its way out, so no sender can leave
 * it off — the branded layout and the designed templates carry it in their
 * own footer, and anything else gets it appended. It is added once only: a
 * message that already says it is left alone.
 *
 * Decorator-free so specs can import it.
 */
export const AUTOMATED_EMAIL_NOTICE =
  'This is an automated email generated by the DBL Group Recruitment System. Please do not reply to this email.';

/** The content id the logo travels under — `<img src="cid:…">`. */
export const EMAIL_LOGO_CID = 'dbl-group-logo';

interface Attachment {
  filename: string;
  content: Buffer;
  contentType?: string;
  /** Set for an image shown inside the message rather than attached to it. */
  cid?: string;
}

interface OutgoingParts {
  text?: string;
  html?: string;
  attachments?: Attachment[];
}

/**
 * Whether the HTML already says it — read as words, so a footer that sets
 * the two sentences on two lines still counts.
 */
export function hasAutomatedNotice(html: string): boolean {
  const words = html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ');
  return words.includes(AUTOMATED_EMAIL_NOTICE);
}

/** The notice as a block of its own, for HTML that has no footer to hold it. */
function noticeBlock(): string {
  return `<div style="margin:28px 0 0;max-width:620px;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.6;color:#64748b">${AUTOMATED_EMAIL_NOTICE}</div>`;
}

/**
 * The message with the notice at its foot, in both versions.
 *
 * A whole HTML document gets it just inside `</body>`; a fragment, or a
 * document with more appended after it (the offer letter falls back to
 * pasting the letter in below its covering note), gets it at the very end.
 */
export function withAutomatedNotice<T extends OutgoingParts>(
  mail: T,
): T & OutgoingParts {
  const out: T & OutgoingParts = { ...mail };
  if (out.text !== undefined && !out.text.includes(AUTOMATED_EMAIL_NOTICE)) {
    out.text = `${out.text.trimEnd()}\n\n—\n${AUTOMATED_EMAIL_NOTICE}`;
  }
  if (out.html !== undefined && !hasAutomatedNotice(out.html)) {
    const end = /<\/body>\s*<\/html>\s*$/i.exec(out.html);
    out.html = end
      ? `${out.html.slice(0, end.index)}${noticeBlock()}\n${out.html.slice(end.index)}`
      : `${out.html}\n${noticeBlock()}`;
  }
  return out;
}

function logoAttachment(): Attachment {
  return {
    filename: 'dbl-group-logo.png',
    content: Buffer.from(EMAIL_LOGO_PNG_BASE64, 'base64'),
    contentType: 'image/png',
    cid: EMAIL_LOGO_CID,
  };
}

/** The logo goes with any message whose HTML shows it — and only those. */
export function withEmailLogo<T extends OutgoingParts>(
  mail: T,
): T & OutgoingParts {
  if (!mail.html?.includes(`cid:${EMAIL_LOGO_CID}`)) return mail;
  if (mail.attachments?.some((a) => a.cid === EMAIL_LOGO_CID)) return mail;
  return {
    ...mail,
    attachments: [...(mail.attachments ?? []), logoAttachment()],
  };
}

/** Everything a message needs before it leaves: the notice, then the logo. */
export function finaliseOutgoing<T extends OutgoingParts>(
  mail: T,
): T & OutgoingParts {
  return withEmailLogo(withAutomatedNotice(mail));
}

/**
 * The HTML with the logo inlined, for showing a message in a browser — the
 * dev server's outbox — where a `cid:` reference resolves to nothing.
 */
export function previewHtml(html: string): string {
  return html
    .split(`cid:${EMAIL_LOGO_CID}`)
    .join(`data:image/png;base64,${EMAIL_LOGO_PNG_BASE64}`);
}
