-- Sub-section: a fourth level under department -> section.
--
-- Cascades from the department+section pair, so `parent` holds "Department||Section".
-- The flat kind='subsection' rows with an empty parent are the complete list,
-- used as a fallback for pairs ZingHR has no specific mapping for.
--
-- Idempotent, same as the other master_options seeds.

-- AlterTable
ALTER TABLE "requisitions" ADD COLUMN "sub_section" VARCHAR(150);

INSERT INTO "master_options" ("id","kind","value","parent","sort_order","updated_at") VALUES
  (gen_random_uuid()::text, 'subsection', 'Accessories', '', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories Central Store', '', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories Store', '', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', '', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts Receivable', '', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts and Treasury', '', 5, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', '', 6, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin, Safety and Security', '', 7, NOW()),
  (gen_random_uuid()::text, 'subsection', 'All Safety Audit', '', 8, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Administration', '', 9, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Development', '', 10, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Support', '', 11, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application and Database Administration', '', 12, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BOQ and Budgeting', '', 13, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BRTA and Documentation', '', 14, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BTL Marketing', '', 15, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Back Process Maintenance', '', 16, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Back and Ring Process Maintenance', '', 17, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Batching Plant', '', 18, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Bestseller', '', 19, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Billing Operation', '', 20, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Bond', '', 21, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', '', 22, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CAD', '', 23, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CCTV Systems', '', 24, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cash Incentive', '', 25, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cash Management', '', 26, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Central Store', '', 27, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ceramic Sales', '', 28, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Civil', '', 29, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Civil Store', '', 30, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Commercial', '', 31, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Communication', '', 32, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Compliance', '', 33, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Construction', '', 34, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Construction Dept.', '', 35, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Core Operation', '', 36, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Corporate Sales', '', 37, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cost and Budget', '', 38, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Custom Bond', '', 39, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Customs Bond', '', 40, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Customs Vat, BERC, BIDA', '', 41, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Customs, City Corporation, Buet', '', 42, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cutting', '', 43, NOW()),
  (gen_random_uuid()::text, 'subsection', 'DBTel Operation', '', 44, NOW()),
  (gen_random_uuid()::text, 'subsection', 'DEEMEXPORT', '', 45, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Data Entry and Processing', '', 46, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dealer Sales', '', 47, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Design Development', '', 48, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Design and Development', '', 49, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Display Center', '', 50, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distribution', '', 51, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distribution Operation', '', 52, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distributionb Department Head', '', 53, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dye House Planning and Coordination', '', 54, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dyeing and Finishing', '', 55, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Electrical', '', 56, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Electro-Mechanical', '', 57, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Embroidery', '', 58, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', '', 59, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Export', '', 60, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Export and Import', '', 61, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fabric store', '', 62, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fashion Design and Product Development', '', 63, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finance', '', 64, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finance and Accounts', '', 65, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finish Fabric', '', 66, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finish Fabric Store', '', 67, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finishing Maintenance', '', 68, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fire Alarm and Safety System', '', 69, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fire and Safety', '', 70, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fixed Asset Management', '', 71, NOW()),
  (gen_random_uuid()::text, 'subsection', 'G-Star', '', 72, NOW()),
  (gen_random_uuid()::text, 'subsection', 'GPQ', '', 73, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Generator and Co-Generation System', '', 74, NOW()),
  (gen_random_uuid()::text, 'subsection', 'George', '', 75, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Gerry Weber', '', 76, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Glazing Line and Printing', '', 77, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Gray Store', '', 78, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Group Accounts', '', 79, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Guess', '', 80, NOW()),
  (gen_random_uuid()::text, 'subsection', 'H and M', '', 81, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR', '', 82, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR Operations', '', 83, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IE', '', 84, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Infrastructure Administration', '', 85, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Planning and Operations', '', 86, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', '', 87, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT and Telecom Support', '', 88, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Import', '', 89, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Import and Export', '', 90, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Inkcups - Tagless Printing', '', 91, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Installation and Servicing', '', 92, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Internal Audit', '', 93, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Justice', '', 94, NOW()),
  (gen_random_uuid()::text, 'subsection', 'K-Mart', '', 95, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Knitting', '', 96, NOW()),
  (gen_random_uuid()::text, 'subsection', 'LIDL', '', 97, NOW()),
  (gen_random_uuid()::text, 'subsection', 'LIFT- Installation and Servicing', '', 98, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Lean Management', '', 99, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Loss Prevention', '', 100, NOW()),
  (gen_random_uuid()::text, 'subsection', 'M and S', '', 101, NOW()),
  (gen_random_uuid()::text, 'subsection', 'MPD', '', 102, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance', '', 103, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance Store', '', 104, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Medical', '', 105, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Merchandising', '', 106, NOW()),
  (gen_random_uuid()::text, 'subsection', 'NOC', '', 107, NOW()),
  (gen_random_uuid()::text, 'subsection', 'NetSuite Implementation', '', 108, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Network Administration', '', 109, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Network Operations', '', 110, NOW()),
  (gen_random_uuid()::text, 'subsection', 'New Frontier', '', 111, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Next', '', 112, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operation', '', 113, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operation-Repaire and Maint-Forklift and Cons.', '', 114, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operations', '', 115, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Outside', '', 116, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PPPL', '', 117, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', '', 118, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Packing', '', 119, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Payroll', '', 120, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Planning', '', 121, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Planning and Implementation', '', 122, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Plant Accounts', '', 123, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Plant Admin', '', 124, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Plant Pre-Audit', '', 125, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Print and Embroidery', '', 126, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Process Development', '', 127, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Procurement', '', 128, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', '', 129, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Coordination', '', 130, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Planning', '', 131, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Staff', '', 132, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Project Management', '', 133, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Projects and Customer Success', '', 134, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', '', 135, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality Control', '', 136, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', '', 137, NOW()),
  (gen_random_uuid()::text, 'subsection', 'RQS', '', 138, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Regulatory Affairs', '', 139, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Repair and Maintenance', '', 140, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ring', '', 141, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ring Maintenance', '', 142, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Rotor', '', 143, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Rupantar Shop-02(Sylhet)', '', 144, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Safety and Security', '', 145, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', '', 146, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample', '', 147, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample Store', '', 148, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Security', '', 149, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sewing', '', 150, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Shipment', '', 151, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Software Customization', '', 152, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sourcing', '', 153, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', '', 154, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sustainability', '', 155, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Administration', '', 156, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Implementation and Support', '', 157, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Integration', '', 158, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Lifecycle Management', '', 159, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Support', '', 160, NOW()),
  (gen_random_uuid()::text, 'subsection', 'TVET', '', 161, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Target Australia', '', 162, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Technical', '', 163, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Telecom Operations', '', 164, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Tom Tailor', '', 165, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Transport', '', 166, NOW()),
  (gen_random_uuid()::text, 'subsection', 'UD.BGMEA', '', 167, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Utility', '', 168, NOW()),
  (gen_random_uuid()::text, 'subsection', 'VAT', '', 169, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', '', 170, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Welfare', '', 171, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', '', 172, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Management', '', 173, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Marketing', '', 174, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Store', '', 175, NOW()),
  (gen_random_uuid()::text, 'subsection', 'ZARA', '', 176, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Accounts Payable', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Accounts Receivable', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts Receivable', 'Accounts and Finance||Accounts Receivable', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Accounts and Finance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts Receivable', 'Accounts and Finance||Accounts and Finance', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cost and Budget', 'Accounts and Finance||Accounts and Finance', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finance', 'Accounts and Finance||Accounts and Finance', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finance and Accounts', 'Accounts and Finance||Accounts and Finance', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Bank Reconciliation', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Corporate Pre Audit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cash Management', 'Accounts and Finance||Finance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Fixed Asset Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fixed Asset Management', 'Accounts and Finance||Fixed Asset Management', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finance', 'Accounts and Finance||Fund Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||GL Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Group Accounts', 'Accounts and Finance||GL Management', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||PF Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Plant Accounts', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Plant Accounts', 'Accounts and Finance||Plant Accounts', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Tax', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||Treasury', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts and Treasury', 'Accounts and Finance||Treasury', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Accounts and Finance||VAT', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'VAT', 'Accounts and Finance||VAT', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Admin, Safety and Security||Admin, Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin, Safety and Security', 'Admin, Safety and Security||Admin, Safety and Security', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Security', 'Admin, Safety and Security||Admin, Safety and Security', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Admin, Safety and Security||Plant Admin', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Security', 'Admin, Safety and Security||Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Batching Plant', 'Batching Plant||Batching Plant', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Billing Operation', 'Billing||Billing Operation', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Communication', 'Brand and Communication||Business Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Communication', 'Brand and Communication||Communication', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Projects and Customer Success', 'Business Development||Business Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Business Development||Business Development', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Import and Export', 'C and F||Export and Import', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CAD', 'CAD||CAD', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cash Incentive', 'Commercial||Cash Incentive', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Export', 'Commercial||Commercial', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Custom Bond', 'Commercial||Customs Bond', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Customs Bond', 'Commercial||Customs Bond', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Customs Vat, BERC, BIDA', 'Commercial||Customs VAT, BERC, BIDA', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Customs, City Corporation, Buet', 'Commercial||Customs, City Corporation, BUET', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'DEEMEXPORT', 'Commercial||Deem Export', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Commercial', 'Commercial||Export', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Export', 'Commercial||Export', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Export and Import', 'Commercial||Export and Import', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Import', 'Commercial||Import', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'UD.BGMEA', 'Commercial||Import', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Commercial', 'Commercial||Textiles Export', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Commercial', 'Commercial||Textiles Import', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Compliance', 'Compliance||Compliance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Compliance', 'Compliance||EMS', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fashion Design and Product Development', 'Compliance||EMS', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Compliance', 'Compliance||Social', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BOQ and Budgeting', 'Construction||BOQ and Budgeting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Construction Dept.', 'Construction||Billing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Civil', 'Construction||Civil', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Construction', 'Construction||Civil', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Civil Store', 'Construction||Civil Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Construction', 'Construction||Construction', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Construction||Construction', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Construction||Construction Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'All Safety Audit', 'Construction||Design,Buyer Accord,Alliance Related Work', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Construction Dept.', 'Construction||Electrical', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Electro-Mechanical', 'Construction||Electro-Mechanical', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Regulatory Affairs', 'Construction||Regulatory Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Construction||Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Support', 'Corporate HR||HR Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR', 'Corporate HR||HR Operations', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR Operations', 'Corporate HR||HR Operations', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Payroll', 'Corporate HR||HR Operations', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cost and Budget', 'Cost and Budget||Corporate Cost and Budget', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cost and Budget', 'Cost and Budget||Plant Cost and Budget', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cutting', 'Cutting||Cutting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'DBTel Operation', 'DBTel||DBTel Operation', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CAD', 'Design and Development||CAD', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Design Development', 'Design and Development||Design and Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Design and Development', 'Design and Development||Design and Development', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Implementation and Support', 'Digital||System Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dye House Planning and Coordination', 'Dye House Planning and Coordination||Dye House Planning and Coordination', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Dyeing||Dyeing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample', 'Dyeing||Sample', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dyeing and Finishing', 'Dyeing||Sub Contract Coordination', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dyeing and Finishing', 'Dyeing and Finishing||Dyeing and Finishing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Enterprise System||Business Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Development', 'Enterprise System||Software Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Software Customization', 'Enterprise System||Software Development', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Integration', 'Enterprise System||Software Development', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'NetSuite Implementation', 'Enterprise System||System Implementation', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Implementation and Support', 'Enterprise System||System Implementation', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Lifecycle Management', 'Enterprise System||System Lifecycle Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Administration', 'Enterprise System||System Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application Support', 'Enterprise System||System Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Data Entry and Processing', 'Enterprise System||System Support', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'Enterprise System||System Support', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Implementation and Support', 'Enterprise System||System Support', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Support', 'Enterprise System||System Support', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Fabric Development||Fabric Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finish Fabric', 'Fabric Development||Sales and Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fashion Design and Product Development', 'Fashion Design and Product Development||Fashion Design and Product Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Finishing||Finishing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fire and Safety', 'Fire and Safety||Fire and Safety', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'GPQ||C and A', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'RQS', 'GPQ||C and A', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'G-Star', 'GPQ||G-STAR', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'GPQ', 'GPQ||GPQ', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Guess', 'GPQ||GUESS', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'GPQ||GUESS', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'GPQ||George', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'GPQ', 'GPQ||H and M', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'GPQ||H and M', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories', 'GPQ||Hugo Boss, Esprit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'GPQ||Hugo Boss, Esprit', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'GPQ||Hugo Boss, Esprit', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'M and S', 'GPQ||M and S', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'New Frontier', 'GPQ||New Frontier', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'GPQ', 'GPQ||Puma', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'GPQ||Puma', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'GPQ||VF ASIA', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'GPQ||Walmart', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'GPQ||Walmart', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'GPQ', 'GPQ||ZARA', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Glazing Line and Printing', 'Glazing Line and Printing||Glazing Line and Printing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Project Management', 'IT Governance||Project Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'IT Infrastructure||IT Infrastructure', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Network Administration', 'IT Infrastructure||IT Infrastructure', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Network Operations', 'IT Infrastructure||IT Infrastructure', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operations', 'IT Infrastructure||IT Infrastructure', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'System Administration', 'IT Infrastructure||IT Infrastructure', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Core Operation', 'IT Infrastructure||IT Infrastructure and Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Infrastructure Administration', 'IT Infrastructure||IT Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Infrastructure Administration', 'IT Infrastructure||IT Planning and Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'IT Infrastructure||IT Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT and Telecom Support', 'IT Infrastructure||IT and Telecom Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Application and Database Administration', 'IT Infrastructure||System Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Telecom Operations', 'IT Infrastructure and Operations||IT Infrastructure', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Planning and Operations', 'IT Infrastructure and Operations||IT Planning and Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'IT Support||IT Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'IT Support||IT Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Network Operations', 'IT Support||IT Support', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'IT Support||Plant IT Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Network Operations', 'IT Support||Plant IT Support', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Support', 'IT and MIS||IT Support', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Process Development', 'IT and MIS||Process Development', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IE', 'Industrial Engineering||Industrial Engineering', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Industrial Engineering||Industrial Engineering', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Industrial Engineering||Industrial Engineering', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Industrial Engineering||Work Study', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CCTV Systems', 'Installation and Servicing||CCTV Systems', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Inkcups - Tagless Printing', 'Installation and Servicing||DBL Distribution Ltd', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Installation and Servicing', 'Installation and Servicing||DBL Distribution Ltd', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fire Alarm and Safety System', 'Installation and Servicing||Fire Alarm and Safety System', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Inkcups - Tagless Printing', 'Installation and Servicing||Inkcups - Tagless Printing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'LIFT- Installation and Servicing', 'Installation and Servicing||Lift Installation and Servicing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Internal Audit', 'Internal Audit||Finance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Internal Audit||Internal Audit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Internal Audit', 'Internal Audit||Internal Audit', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Electro-Mechanical', 'Lab||Dye House Lab', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Lean Management', 'Lean Management||Lean Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Lean Management||Lean Management', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Loss Prevention', 'Loss Prevention||Loss Prevention', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CAD', 'MPD||CAD', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'MPD', 'MPD||MPD', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'MPD||MPD', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'MPD||MPD', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Back Process Maintenance', 'Maintenance||Maintenance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Back and Ring Process Maintenance', 'Maintenance||Maintenance', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finishing Maintenance', 'Maintenance||Maintenance', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance', 'Maintenance||Maintenance', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ring Maintenance', 'Maintenance||Maintenance', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IT Infrastructure Administration', 'Manufacturing||Manufacturing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BTL Marketing', 'Marketing||BTL Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BTL Marketing', 'Marketing||Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PPPL', 'Marketing||Marketing', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Marketing||Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Outside', 'Marketing||Yarn Marketing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Marketing', 'Marketing||Yarn Marketing', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Medical', 'Medical||Medical', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Bestseller', 'Merchandising||Bestseller', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'George', 'Merchandising||Bestseller', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'K-Mart', 'Merchandising||Bestseller', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Next', 'Merchandising||Bonita', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'Merchandising||C and A', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'Merchandising||C and A', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Merchandising', 'Merchandising||C and A', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'ZARA', 'Merchandising||C and A', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Merchandising||Camel Active', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'Merchandising||Esprit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Gerry Weber', 'Merchandising||Esprit', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Guess', 'Merchandising||Esprit', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'LIDL', 'Merchandising||Esprit', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Merchandising||Esprit', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'G-Star', 'Merchandising||G-STAR', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Merchandising', 'Merchandising||G-STAR', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'Merchandising||G-STAR', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Guess', 'Merchandising||GUESS', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'M and S', 'Merchandising||GUESS', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Merchandising', 'Merchandising||GUESS', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Next', 'Merchandising||GUESS', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Tom Tailor', 'Merchandising||GUESS', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'George', 'Merchandising||George', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'K-Mart', 'Merchandising||George', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'Merchandising||H and M', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'H and M', 'Merchandising||H and M', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Next', 'Merchandising||H and M', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'Merchandising||Hugo Boss', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Justice', 'Merchandising||Justice', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'George', 'Merchandising||K-Mart', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'K-Mart', 'Merchandising||K-Mart', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'M and S', 'Merchandising||M and S', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'Merchandising||Merchandising', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'Merchandising||Merchandising', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'H and M', 'Merchandising||Merchandising', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Merchandising', 'Merchandising||Merchandising', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Next', 'Merchandising||Merchandising', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Merchandising||Merchandising', 5, NOW()),
  (gen_random_uuid()::text, 'subsection', 'LIDL', 'Merchandising||New Frontier', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'Merchandising||New Frontier', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Merchandising||Puma', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'Merchandising||Ralph Lauren', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Target Australia', 'Merchandising||Target Australia', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Tom Tailor', 'Merchandising||Tom Tailor', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Esprit', 'Merchandising||VF ASIA', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'Merchandising||VF ASIA', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'Merchandising||Vouge Sourcing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Bestseller', 'Merchandising||Walmart', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'ZARA', 'Merchandising||ZARA', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'NOC', 'NOC||Telecom NOC', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distribution Operation', 'Operations||DBL Distribution Ltd', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distributionb Department Head', 'Operations||DBL Distribution Ltd', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operations', 'Operations||Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Operations||Production', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Planning', 'Planning||Planning', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Planning', 'Planning||Planning', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Planning||Production Planning', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Planning and Implementation', 'Planning and Implementation||Planning and Implementation', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Plant Admin||Admin, Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Plant Admin||Corporate Admin', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Plant Admin||Plant Admin', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Plant Admin', 'Plant Admin||Plant Admin', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Shipment', 'Plant Admin||Plant Admin', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Shipment', 'Plant Admin||Shipment', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Transport', 'Plant Admin||Transport', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Plant HR||HR Operations', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR', 'Plant HR||HR Operations', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR Operations', 'Plant HR||HR Operations', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Welfare', 'Plant HR||HR Operations', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR', 'Plant HR||Welfare', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'HR Operations', 'Plant HR||Welfare', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Welfare', 'Plant HR||Welfare', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Pre-Audit||Corporate Pre Audit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accounts', 'Pre-Audit||Group Finance-Internal Audit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Plant Pre-Audit', 'Pre-Audit||Plant Pre-Audit', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Procurement', 'Procurement||Procurement', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sourcing', 'Procurement||Yarn', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production||Body Preparation', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cutting', 'Production||Cutting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production||Cutting', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Embroidery', 'Production||Embroidery', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production||Embroidery', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'IE', 'Production||Industrial Engineering', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production||Knitting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Lean Management', 'Production||Lean Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Packing', 'Production||Packing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance', 'Production||Press and Dryer', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Production||Press and Dryer', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Technical', 'Production||Press and Dryer', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Print and Embroidery', 'Production||Print and Embroidery', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production||Print and Embroidery', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Cutting', 'Production||Production', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Embroidery', 'Production||Production', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fashion Design and Product Development', 'Production||Production', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production||Production', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Coordination', 'Production||Production', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Staff', 'Production||Production', 5, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'Production||Production', 6, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sewing', 'Production||Production', 7, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Technical', 'Production||Production', 8, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Production||Production', 9, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'Production||R and D', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ring', 'Production||Ring', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Rotor', 'Production||Rotor', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample', 'Production||Sample', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sewing', 'Production||Sewing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production Coordination||Knitting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Knitting', 'Production Coordination||Production Coordination', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Production Coordination||Production Coordination', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Coordination', 'Production Coordination||Production Coordination', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'Production Coordination||Production Coordination', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Planning', 'Production Planning||Planning', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Planning', 'Production Planning||Planning', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Production Planning||Planning', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fashion Design and Product Development', 'Production Planning||Production Planning', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Planning', 'Production Planning||Production Planning', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production Planning', 'Production Planning||Production Planning', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sourcing', 'Production Planning||Production Planning', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Production Planning||Production Planning', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Quality||Production', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Quality||Quality', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'Quality||Quality', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'Quality Control||Knitting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'GPQ', 'Quality Control||Quality', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'Quality Control||Quality', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance', 'Quality Control||Quality Control', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Quality Control||Quality Control', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality Control', 'Quality Control||Quality Control', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'R and D||Knitting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'R and D||R and D', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fashion Design and Product Development', 'RQS||C and A', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'RQS', 'RQS||C and A', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Quality', 'RQS||H and M', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'RQS', 'RQS||H and M', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'H and M', 'RQS||RQS', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'RQS', 'RQS||RQS', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distributionb Department Head', 'Regulatory Affairs||Regulatory Affairs', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Retail Sales||Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Retail Sales||Sales', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Bond', 'SCM||Bond', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'SCM||Supply Chain', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operations', 'Safety and Security||CCTV', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fire and Safety', 'Safety and Security||Fire and Safety', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fire and Safety', 'Safety and Security||Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Safety and Security', 'Safety and Security||Safety and Security', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Security', 'Safety and Security||Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ceramic Sales', 'Sales||Ceramic Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Corporate Sales', 'Sales||Corporate Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Sales||Corporate Sales', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ceramic Sales', 'Sales||Dealer Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dealer Sales', 'Sales||Dealer Sales', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Display Center', 'Sales||Dealer Sales', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Sales||Dealer Sales', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Display Center', 'Sales||Display Center', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Sales||Display Center', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Distribution', 'Sales||Distribution', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample', 'Sales||Retail Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Ceramic Sales', 'Sales||Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Corporate Sales', 'Sales||Sales', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dealer Sales', 'Sales||Sales', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Rupantar Shop-02(Sylhet)', 'Sales||Sales', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Sales||Sales', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sales', 'Sales and Distribution||Sales', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Inkcups - Tagless Printing', 'Sales and Marketing||Inkcups - Tagless Printing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample', 'Sample||Embroidery', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Sample||GPQ', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'Sample||Quality', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'G-Star', 'Sample||Quality', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'Sample||Quality', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'C and A', 'Sample||Sample', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'CCTV Systems', 'Sample||Sample', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'G-Star', 'Sample||Sample', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'H and M', 'Sample||Sample', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Next', 'Sample||Sample', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'PUMA', 'Sample||Sample', 5, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Sample||Sample', 6, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample', 'Sample||Sample', 7, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Walmart', 'Sample||Sample', 8, NOW()),
  (gen_random_uuid()::text, 'subsection', 'MPD', 'Security||Safety and Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Security', 'Security||Safety and Security', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Security', 'Security||Security', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sourcing', 'Sourcing||Sourcing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Dealer Sales', 'Stock||Stock', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories', 'Store||Accessories Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories Central Store', 'Store||Accessories Store', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories Store', 'Store||Accessories Store', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Central Store', 'Store||Accessories Store', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Store||Accessories Store', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Accessories Store', 'Store||Bhuyan Bari Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample Store', 'Store||Bhuyan Bari Store', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Fabric store', 'Store||Fabric Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finish Fabric', 'Store||Finish Fabric Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finish Fabric Store', 'Store||Finish Fabric Store', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Store||Finish Fabric Store', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Gray Store', 'Store||Grey Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Store||Grey Store', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Store', 'Store||Grey Store', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance Store', 'Store||Maintenance Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sample Store', 'Store||Sample Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finish Fabric Store', 'Store||Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Store||Store', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Store', 'Store||Store', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Utility', 'Store||Store', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Maintenance Store', 'Store||Yarn Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Store', 'Store||Yarn Store', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Sustainability', 'Sustainability||Sustainability', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'TVET', 'TVET||TVET', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Technical', 'Technical||Embroidery', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Technical', 'Technical||Knitting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Technical||Technical', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Technical', 'Technical||Technical', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Telecom Operations', 'Telecom||Billing', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'BRTA and Documentation', 'Transport||Transport', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operation', 'Transport||Transport', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Operation-Repaire and Maint-Forklift and Cons.', 'Transport||Transport', 2, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Repair and Maintenance', 'Transport||Transport', 3, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Transport', 'Transport||Transport', 4, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Finance', 'Treasury||Accounts and Finance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Electrical', 'Utility||Electrical', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Generator and Co-Generation System', 'Utility||Generator and Co-Generation System', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Utility', 'Utility||Knitting', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Utility', 'Utility||Maintenance', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Utility', 'Utility||Utility', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Central Store', 'VTS Monitoring||Accessories Store', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'Washing||Production', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'R and D', 'Washing||R and D', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Work Study||Lean Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Work Study', 'Work Study||Work Study', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Production', 'Yarn Management||Yarn Management', 0, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Yarn Management', 'Yarn Management||Yarn Management', 1, NOW()),
  (gen_random_uuid()::text, 'subsection', 'Admin', 'Zoo||Zoo', 0, NOW())
ON CONFLICT ("kind","value","parent") DO NOTHING;
