import { bdjobsToCvProfile } from './bdjobs-cv.mapper';
import { bdjobsProfileToCandidateData } from './bdjobs-profile.adapter';
import { buildCvDocument } from './cv-document';

const NOW = new Date('2026-09-14T00:00:00.000Z');

/** Strip markup so an assertion reads the page, not the styling. */
const text = (html: string) =>
  html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&#39;|&quot;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();

/**
 * The nested CandidateData shape, structurally as Bdjobs sends it, with
 * invented values — real applicant details do not belong in a repository.
 */
const NESTED = {
  personalData: {
    salutation: 'Mr.',
    fullName: 'Test Applicant',
    firstName: 'Test',
    lastName: 'Applicant',
    requisitionId: 'REQ-2026-001',
    countryCode: '+880',
    mobileNo: '01800000000',
    Dob: '01/07/1990',
    emailId: 'test.applicant@example.invalid',
    gender: 'Male',
    currentAddress1: '1 Example Road, Dhaka',
    currentSalary: 10000,
    expectedSalary: null,
    MaritalStatus: 'Unmarried',
  },
  EmploymentHistory: [
    {
      companyName: 'Example Ltd',
      designation: 'Analyst',
      role: '',
      fromDate: '01/12/2018',
      toDate: '14/09/2026',
    },
  ],
  qualifications: [
    {
      university: 'Example University',
      institute: 'Example University',
      country: 'Bangladesh',
      passYear: 2013,
      grade: '',
      percentage: '45%',
    },
  ],
};

/** The flat `profile` shape the live job board posts. */
const FLAT = {
  currentEmployer: 'Example Ltd',
  currentDesignation: 'Officer',
  expectedSalary: 0,
  currentSalary: 0,
  institution: 'Example College',
  passingYear: 2016,
  presentLocation: 'Dhaka',
  dateOfBirth: '1988-01-01',
  gender: 'Female',
  employmentHistory: [
    { companyName: 'Alpha Ltd', designation: 'Officer', fromDate: '02/01/2012', toDate: '14/09/2026' },
    { companyName: 'Beta Ltd', designation: 'Executive', fromDate: '02/11/2001', toDate: '14/09/2026' },
  ],
  educationHistory: [
    { institute: 'govt girl``````s school', passingYear: 2014, percentage: '60%' },
    { institute: 'Example College', passingYear: 2016, percentage: '45%' },
  ],
};

describe('buildCvDocument — the nested CandidateData application', () => {
  const cv = bdjobsToCvProfile(NESTED, NOW);
  const html = buildCvDocument(cv, NOW);
  const body = text(html);

  it('leads with who the candidate is and how to reach them', () => {
    expect(body).toContain('Mr. Test Applicant');
    expect(body).toContain('test.applicant@example.invalid');
    expect(body).toContain('+880 01800000000');
  });

  it('shows the facts a recruiter reads first', () => {
    expect(body).toContain('Total experience');
    expect(body).toContain('Currently at');
    expect(body).toContain('Example Ltd — Analyst');
    expect(body).toContain('Latest education');
  });

  it('renders the employment history with a readable period', () => {
    expect(body).toContain('Professional Experience');
    expect(body).toContain('Dec 2018 – Present');
    expect(body).toContain('Analyst');
    expect(body).toContain('CURRENT');
  });

  it('renders education with year, institute and result', () => {
    expect(body).toContain('Education');
    expect(body).toContain('Example University');
    expect(body).toContain('2013');
    expect(body).toContain('45%');
  });

  it('includes personal details that were actually supplied', () => {
    expect(body).toContain('Personal Details');
    expect(body).toContain('Unmarried');
    expect(body).toContain('1 Example Road, Dhaka');
    // Nothing was sent for these, so no empty rows.
    expect(body).not.toContain('Blood group');
  });

  it('says it was generated, and from what', () => {
    // An interviewer who thinks the candidate wrote this will read omissions
    // as the candidate's choices. They are Bdjobs' form design.
    expect(body).toContain('Generated by DBL HRM from the BDJobs application');
    expect(body).toContain('14 September 2026');
    expect(body).toContain('not a CV they wrote');
  });
});

describe('buildCvDocument — the flat profile application', () => {
  const data = bdjobsProfileToCandidateData(FLAT, {
    name: 'Test Applicant Two',
    email: 'two@example.invalid',
    phone: '+880000000000',
  });
  const cv = bdjobsToCvProfile(data!, NOW);
  const body = text(buildCvDocument(cv, NOW));

  it('renders the same document from the other payload shape', () => {
    expect(body).toContain('Test Applicant Two');
    expect(body).toContain('Professional Experience');
    expect(body).toContain('Alpha Ltd');
    expect(body).toContain('Dhaka');
  });

  it('does not claim a salary when Bdjobs sent 0 for "not stated"', () => {
    expect(body).not.toContain('Expected salary');
    expect(body).not.toContain('Current salary');
  });

  it("tidies Bdjobs' backtick padding", () => {
    expect(body).toContain("govt girl's school");
    expect(body).not.toContain('``');
  });

  it('counts overlapping jobs once', () => {
    // 2001 to 2026 is about 24 years. Adding the two spans would claim ~39.
    const years = Number(/([\d.]+)/.exec(cv.summary.totalExperienceYears + '')?.[1]);
    expect(years).toBeGreaterThan(24);
    expect(years).toBeLessThan(25);
  });
});

describe('buildCvDocument — degenerate input', () => {
  it('renders without throwing when almost nothing was supplied', () => {
    const cv = bdjobsToCvProfile({ personalData: {} }, NOW);
    const html = buildCvDocument(cv, NOW);
    expect(html).toContain('Candidate name not supplied');
    // No invented sections for data that does not exist.
    expect(text(html)).not.toContain('Professional Experience');
    expect(text(html)).not.toContain('Education');
  });

  it('escapes markup rather than emitting it', () => {
    const cv = bdjobsToCvProfile(
      { personalData: { fullName: '<script>alert(1)</script>' } },
      NOW,
    );
    const html = buildCvDocument(cv, NOW);
    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;');
  });
});
